language: node_js
node_js:
- '8'
branches:
  only:
  - nightly
  - master
  - sandbox
script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 194.87.110.17 >> ~/.ssh/known_hosts
- chmod 600 $HOME/.ssh/github_deploy_key
- ssh-add $HOME/.ssh/github_deploy_key
- npm run build
- scp -r ./public fourtytwo@194.87.110.17:~/frontend
before_install:
- openssl aes-256-cbc -K $encrypted_a9ffcaf94a53_key -iv $encrypted_a9ffcaf94a53_iv
  -in github_deploy_key.enc -out $HOME/.ssh/github_deploy_key -d

